name: dropdown_date_picker 
description: A dropdown date picker package for date selection like year, month and day.
version: 0.1.1+2
issue_tracker: https://gitlab.com/Patesz/dropdown_datepicker/issues
homepage: https://gitlab.com/Patesz/dropdown_datepicker

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2

flutter:

