name: dropdown_date_picker
description: A dropdown date picker package for date selection like year, month and day.
version: 0.2.0
issue_tracker: https://github.com/najeira/flutter-packages/issues
homepage: https://github.com/najeira/flutter-packages

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
