name: dialog
description: Dialog utilities for Flutter.
version: 0.0.2
author: najeira
homepage: https://github.com/najeira

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0
