name: dialog
description: Dialog utilities for Flutter.
version: 0.2.0
author: najeira <najeira@gmail.com>
homepage: https://github.com/najeira/flutter-packages

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
