name: dialog
description: Dialog utilities for Flutter.
version: 0.3.1
homepage: https://github.com/najeira/flutter-packages
repository: https://github.com/najeira/flutter-packages

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
